version: '3.8'
services:
  mysql:
    container_name: mysql-demo
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp